services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile.python
    env_file: .env
    stdin_open: true
    tty: true

  ts-server:
    build:
      context: ./ts-server
      dockerfile: Dockerfile.node
    env_file: .env
    stdin_open: true
    tty: true
